DROP SCHEMA IF EXISTS coad_web CASCADE;
CREATE SCHEMA coad_web;

CREATE TABLE IF NOT EXISTS coad_web.mutation_gene_frequencies (
  gene_symbol text PRIMARY KEY,
  mutation_records integer NOT NULL,
  mutated_sample_count integer NOT NULL,
  mutated_sample_percent numeric(6, 2) NOT NULL,
  top_variant_classification text,
  source_schema text NOT NULL DEFAULT 'bio_tcga',
  source_table text NOT NULL DEFAULT 'mc3_public_maf',
  display_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS coad_web.protein_structure_targets (
  gene_symbol text PRIMARY KEY,
  protein_name text NOT NULL,
  uniprot_id text NOT NULL,
  alphafold_url text NOT NULL,
  protein_length integer,
  project_reason text NOT NULL,
  structure_note text NOT NULL,
  source_note text NOT NULL DEFAULT 'Curated public protein metadata for website display'
);

CREATE TABLE IF NOT EXISTS coad_web.mutation_hotspots (
  hotspot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gene_symbol text NOT NULL REFERENCES coad_web.mutation_gene_frequencies(gene_symbol) ON DELETE CASCADE,
  protein_change text NOT NULL,
  amino_acid_position integer,
  amino_acids text,
  mutation_label text NOT NULL DEFAULT 'Hotspot',
  sample_count integer NOT NULL,
  mutation_records integer NOT NULL,
  variant_classification text,
  cbioportal_mutation_mapper_url text NOT NULL,
  source_schema text NOT NULL DEFAULT 'bio_tcga',
  source_table text NOT NULL DEFAULT 'mc3_public_maf',
  display_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS coad_web.coad_drug_sources (
  source_key text PRIMARY KEY,
  source_name text NOT NULL,
  source_url text NOT NULL,
  used_for text NOT NULL,
  access_date date NOT NULL,
  source_note text NOT NULL
);

CREATE TABLE IF NOT EXISTS coad_web.coad_treatment_drugs (
  drug_slug text PRIMARY KEY,
  drug_name text NOT NULL,
  nci_drug_url text NOT NULL,
  nci_cancer_type text NOT NULL DEFAULT 'Colon and rectal cancer',
  evidence_label text NOT NULL DEFAULT 'NCI colorectal cancer drug list',
  source_key text NOT NULL REFERENCES coad_web.coad_drug_sources(source_key),
  display_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS coad_web.coad_drug_compounds (
  compound_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_slug text NOT NULL REFERENCES coad_web.coad_treatment_drugs(drug_slug) ON DELETE CASCADE,
  drug_name text NOT NULL,
  compound_name text NOT NULL,
  chembl_id text NOT NULL,
  molregno integer,
  molecular_formula text,
  canonical_smiles text,
  standard_inchi_key text,
  max_phase numeric,
  molecule_type text,
  structure_image_url_or_svg text,
  chembl_source_note text NOT NULL DEFAULT 'Curated from local chembl schema',
  source_schema text NOT NULL DEFAULT 'chembl',
  source_table text NOT NULL DEFAULT 'molecule_dictionary, compound_properties, compound_structures',
  UNIQUE (drug_slug, chembl_id)
);

CREATE TABLE IF NOT EXISTS coad_web.coad_drug_indications (
  indication_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_slug text NOT NULL REFERENCES coad_web.coad_treatment_drugs(drug_slug) ON DELETE CASCADE,
  chembl_id text,
  indication_text text,
  mesh_heading text,
  efo_term text,
  source_schema text NOT NULL DEFAULT 'chembl',
  source_table text NOT NULL DEFAULT 'drug_indication'
);

WITH coad_maf AS (
  SELECT
    m.tumor_sample_barcode,
    m.hugo_symbol,
    m.variant_classification
  FROM bio_tcga.mc3_public_maf m
  JOIN bio_tcga.tcga_cdr_tcga_cdr c
    ON c.type = 'COAD'
   AND c.bcr_patient_barcode = substring(m.tumor_sample_barcode from 1 for 12)
  WHERE COALESCE(m.hugo_symbol, '') NOT IN ('', 'Unknown')
),
sample_denominator AS (
  SELECT COUNT(DISTINCT tumor_sample_barcode)::numeric AS sample_count
  FROM coad_maf
),
gene_counts AS (
  SELECT
    hugo_symbol,
    COUNT(*)::int AS mutation_records,
    COUNT(DISTINCT tumor_sample_barcode)::int AS mutated_samples
  FROM coad_maf
  GROUP BY hugo_symbol
),
variant_rank AS (
  SELECT
    hugo_symbol,
    variant_classification,
    ROW_NUMBER() OVER (
      PARTITION BY hugo_symbol
      ORDER BY COUNT(*) DESC, variant_classification
    ) AS variant_rank
  FROM coad_maf
  GROUP BY hugo_symbol, variant_classification
),
ranked_genes AS (
  SELECT
    g.hugo_symbol,
    g.mutation_records,
    g.mutated_samples,
    ROUND(100.0 * g.mutated_samples / NULLIF(d.sample_count, 0), 2) AS sample_frequency_pct,
    v.variant_classification,
    ROW_NUMBER() OVER (ORDER BY g.mutated_samples DESC, g.mutation_records DESC, g.hugo_symbol) AS display_order
  FROM gene_counts g
  CROSS JOIN sample_denominator d
  LEFT JOIN variant_rank v
    ON v.hugo_symbol = g.hugo_symbol
   AND v.variant_rank = 1
)
INSERT INTO coad_web.mutation_gene_frequencies (
  gene_symbol,
  mutation_records,
  mutated_sample_count,
  mutated_sample_percent,
  top_variant_classification,
  display_order
)
SELECT
  hugo_symbol,
  mutation_records,
  mutated_samples,
  sample_frequency_pct,
  variant_classification,
  display_order
FROM ranked_genes
WHERE display_order <= 30
   OR hugo_symbol IN ('APC', 'TP53', 'KRAS', 'BRAF', 'PIK3CA', 'SMAD4')
ORDER BY display_order;

INSERT INTO coad_web.protein_structure_targets (
  gene_symbol,
  protein_name,
  uniprot_id,
  alphafold_url,
  protein_length,
  project_reason,
  structure_note
)
VALUES
  ('APC', 'Adenomatous polyposis coli protein', 'P25054', 'https://alphafold.ebi.ac.uk/entry/P25054', 2843, 'APC is the most frequently mutated COAD gene in this project summary and is a classic colorectal cancer gene.', 'AlphaFold DB provides a predicted structure. APC is a large protein, so use the external AlphaFold view for detailed inspection.'),
  ('TP53', 'Cellular tumor antigen p53', 'P04637', 'https://alphafold.ebi.ac.uk/entry/P04637', 393, 'TP53 is frequently mutated in COAD and is linked to DNA damage control.', 'AlphaFold structures are predicted protein shapes and should be read as research context only.'),
  ('KRAS', 'KRAS proto-oncogene, GTPase', 'P01116', 'https://alphafold.ebi.ac.uk/entry/P01116', 189, 'KRAS is a frequently mutated COAD gene and affects cell-growth signaling.', 'AlphaFold DB provides a predicted reference structure. Hotspot locations are shown as educational context.'),
  ('BRAF', 'B-Raf proto-oncogene, serine/threonine kinase', 'P15056', 'https://alphafold.ebi.ac.uk/entry/P15056', 766, 'BRAF p.V600E is a well-known cancer hotspot and appears in the COAD hotspot summary.', 'The AlphaFold confidence near some flexible regions can be lower than for compact protein regions.'),
  ('PIK3CA', 'Phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit alpha', 'P42336', 'https://alphafold.ebi.ac.uk/entry/P42336', 1068, 'PIK3CA is a common COAD mutation gene involved in growth signaling pathways.', 'The selected hotspot connects mutation counts with protein-level biology.'),
  ('SMAD4', 'Mothers against decapentaplegic homolog 4', 'Q13485', 'https://alphafold.ebi.ac.uk/entry/Q13485', 552, 'SMAD4 is a classic colorectal cancer gene in the TGF-beta cell communication pathway.', 'AlphaFold gives a predicted structure for learning and visualization, not a clinical interpretation.')
ON CONFLICT (gene_symbol) DO UPDATE SET
  protein_name = EXCLUDED.protein_name,
  uniprot_id = EXCLUDED.uniprot_id,
  alphafold_url = EXCLUDED.alphafold_url,
  protein_length = EXCLUDED.protein_length,
  project_reason = EXCLUDED.project_reason,
  structure_note = EXCLUDED.structure_note;

WITH coad_maf AS (
  SELECT
    m.tumor_sample_barcode,
    m.hugo_symbol,
    m.hgvsp_short,
    m.protein_position,
    m.amino_acids,
    m.variant_classification
  FROM bio_tcga.mc3_public_maf m
  JOIN bio_tcga.tcga_cdr_tcga_cdr c
    ON c.type = 'COAD'
   AND c.bcr_patient_barcode = substring(m.tumor_sample_barcode from 1 for 12)
  WHERE COALESCE(m.hugo_symbol, '') NOT IN ('', 'Unknown')
    AND m.hgvsp_short LIKE 'p.%'
    AND m.hgvsp_short <> 'p.?'
),
hotspots AS (
  SELECT
    hugo_symbol,
    hgvsp_short,
    NULLIF(regexp_replace(split_part(COALESCE(protein_position, ''), '/', 1), '[^0-9]', '', 'g'), '')::int AS amino_acid_position,
    amino_acids,
    variant_classification,
    COUNT(DISTINCT tumor_sample_barcode)::int AS mutated_samples,
    COUNT(*)::int AS mutation_records,
    ROW_NUMBER() OVER (
      ORDER BY COUNT(DISTINCT tumor_sample_barcode) DESC, COUNT(*) DESC, hugo_symbol, hgvsp_short
    ) AS display_order
  FROM coad_maf
  GROUP BY hugo_symbol, hgvsp_short, protein_position, amino_acids, variant_classification
  HAVING COUNT(DISTINCT tumor_sample_barcode) >= 3
)
INSERT INTO coad_web.mutation_hotspots (
  gene_symbol,
  protein_change,
  amino_acid_position,
  amino_acids,
  sample_count,
  mutation_records,
  variant_classification,
  cbioportal_mutation_mapper_url,
  display_order
)
SELECT
  h.hugo_symbol,
  h.hgvsp_short,
  h.amino_acid_position,
  h.amino_acids,
  h.mutated_samples,
  h.mutation_records,
  h.variant_classification,
  'https://www.cbioportal.org/mutation_mapper?standaloneMutationMapperGeneTab=' || h.hugo_symbol,
  h.display_order
FROM hotspots h
JOIN coad_web.mutation_gene_frequencies g
  ON g.gene_symbol = h.hugo_symbol
WHERE h.display_order <= 30
ORDER BY h.display_order;

INSERT INTO coad_web.coad_drug_sources (
  source_key,
  source_name,
  source_url,
  used_for,
  access_date,
  source_note
)
VALUES (
  'nci_colorectal_drugs',
  'National Cancer Institute: Drugs Approved for Colon and Rectal Cancer',
  'https://www.cancer.gov/about-cancer/treatment/drugs/colorectal',
  'Source list for COAD/colorectal treatment drug names on the website',
  CURRENT_DATE,
  'Drug names are used for educational treatment context only, not treatment advice.'
);

INSERT INTO coad_web.coad_treatment_drugs (
  drug_slug,
  drug_name,
  nci_drug_url,
  evidence_label,
  source_key,
  display_order
)
VALUES
  ('fluorouracil', 'Fluorouracil', 'https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil', 'NCI listed drug', 'nci_colorectal_drugs', 1),
  ('oxaliplatin', 'Oxaliplatin', 'https://www.cancer.gov/about-cancer/treatment/drugs/oxaliplatin', 'NCI listed drug', 'nci_colorectal_drugs', 2),
  ('irinotecan', 'Irinotecan Hydrochloride', 'https://www.cancer.gov/about-cancer/treatment/drugs/irinotecanhydrochloride', 'NCI listed drug', 'nci_colorectal_drugs', 3),
  ('capecitabine', 'Capecitabine', 'https://www.cancer.gov/about-cancer/treatment/drugs/capecitabine', 'NCI listed drug', 'nci_colorectal_drugs', 4),
  ('regorafenib', 'Regorafenib', 'https://www.cancer.gov/about-cancer/treatment/drugs/regorafenib', 'NCI listed drug', 'nci_colorectal_drugs', 5),
  ('fruquintinib', 'Fruquintinib', 'https://www.cancer.gov/about-cancer/treatment/drugs/fruquintinib', 'NCI listed drug', 'nci_colorectal_drugs', 6),
  ('sotorasib', 'Sotorasib', 'https://www.cancer.gov/about-cancer/treatment/drugs/sotorasib', 'NCI listed drug', 'nci_colorectal_drugs', 7),
  ('adagrasib', 'Adagrasib', 'https://www.cancer.gov/about-cancer/treatment/drugs/adagrasib', 'NCI listed drug', 'nci_colorectal_drugs', 8),
  ('tucatinib', 'Tucatinib', 'https://www.cancer.gov/about-cancer/treatment/drugs/tucatinib', 'NCI listed drug', 'nci_colorectal_drugs', 9),
  ('trifluridine-tipiracil', 'Trifluridine and Tipiracil Hydrochloride', 'https://www.cancer.gov/about-cancer/treatment/drugs/trifluridine-tipiracilhydrochloride', 'NCI listed drug combination', 'nci_colorectal_drugs', 10),
  ('leucovorin', 'Leucovorin Calcium', 'https://www.cancer.gov/about-cancer/treatment/drugs/leucovorincalcium', 'NCI listed drug', 'nci_colorectal_drugs', 11),
  ('bevacizumab', 'Bevacizumab', 'https://www.cancer.gov/about-cancer/treatment/drugs/bevacizumab', 'NCI listed biologic', 'nci_colorectal_drugs', 12),
  ('cetuximab', 'Cetuximab', 'https://www.cancer.gov/about-cancer/treatment/drugs/cetuximab', 'NCI listed biologic', 'nci_colorectal_drugs', 13),
  ('panitumumab', 'Panitumumab', 'https://www.cancer.gov/about-cancer/treatment/drugs/panitumumab', 'NCI listed biologic', 'nci_colorectal_drugs', 14),
  ('pembrolizumab', 'Pembrolizumab', 'https://www.cancer.gov/about-cancer/treatment/drugs/pembrolizumab', 'NCI listed immunotherapy', 'nci_colorectal_drugs', 15),
  ('nivolumab', 'Nivolumab', 'https://www.cancer.gov/about-cancer/treatment/drugs/Nivolumab', 'NCI listed immunotherapy', 'nci_colorectal_drugs', 16),
  ('ipilimumab', 'Ipilimumab', 'https://www.cancer.gov/about-cancer/treatment/drugs/ipilimumab', 'NCI listed immunotherapy', 'nci_colorectal_drugs', 17),
  ('ramucirumab', 'Ramucirumab', 'https://www.cancer.gov/about-cancer/treatment/drugs/ramucirumab', 'NCI listed biologic', 'nci_colorectal_drugs', 18),
  ('ziv-aflibercept', 'Ziv-Aflibercept', 'https://www.cancer.gov/about-cancer/treatment/drugs/ziv-aflibercept', 'NCI listed biologic', 'nci_colorectal_drugs', 19);

WITH drug_aliases(drug_slug, search_name, preferred_chembl_id, alias_order) AS (
  VALUES
    ('fluorouracil', 'Fluorouracil', 'CHEMBL185', 1),
    ('oxaliplatin', 'Oxaliplatin', 'CHEMBL414804', 1),
    ('irinotecan', 'Irinotecan', 'CHEMBL481', 1),
    ('capecitabine', 'Capecitabine', 'CHEMBL1773', 1),
    ('regorafenib', 'Regorafenib', 'CHEMBL1946170', 1),
    ('fruquintinib', 'Fruquintinib', NULL, 1),
    ('sotorasib', 'Sotorasib', NULL, 1),
    ('adagrasib', 'Adagrasib', NULL, 1),
    ('tucatinib', 'Tucatinib', NULL, 1),
    ('trifluridine-tipiracil', 'Trifluridine', NULL, 1),
    ('trifluridine-tipiracil', 'Tipiracil', NULL, 2),
    ('leucovorin', 'Leucovorin', NULL, 1),
    ('leucovorin', 'Leucovorin Calcium', NULL, 2),
    ('bevacizumab', 'Bevacizumab', NULL, 1),
    ('cetuximab', 'Cetuximab', NULL, 1),
    ('panitumumab', 'Panitumumab', NULL, 1),
    ('pembrolizumab', 'Pembrolizumab', NULL, 1),
    ('nivolumab', 'Nivolumab', NULL, 1),
    ('ipilimumab', 'Ipilimumab', NULL, 1),
    ('ramucirumab', 'Ramucirumab', NULL, 1),
    ('ziv-aflibercept', 'Aflibercept', NULL, 1)
),
id_matches AS (
  SELECT
    a.drug_slug,
    a.alias_order,
    md.molregno,
    md.chembl_id,
    md.pref_name,
    md.max_phase,
    md.molecule_type,
    0 AS match_priority
  FROM drug_aliases a
  JOIN chembl.molecule_dictionary md
    ON md.chembl_id = a.preferred_chembl_id
  WHERE a.preferred_chembl_id IS NOT NULL
),
name_matches AS (
  SELECT
    a.drug_slug,
    a.alias_order,
    md.molregno,
    md.chembl_id,
    md.pref_name,
    md.max_phase,
    md.molecule_type,
    1 AS match_priority
  FROM drug_aliases a
  JOIN chembl.molecule_dictionary md
    ON md.pref_name = upper(a.search_name)
  WHERE a.preferred_chembl_id IS NULL
),
all_matches AS (
  SELECT * FROM id_matches
  UNION ALL
  SELECT * FROM name_matches
),
ranked_matches AS (
  SELECT DISTINCT ON (drug_slug, chembl_id)
    drug_slug,
    molregno,
    chembl_id,
    pref_name,
    max_phase,
    molecule_type,
    alias_order
  FROM all_matches
  ORDER BY drug_slug, chembl_id, match_priority, alias_order, max_phase DESC NULLS LAST
)
INSERT INTO coad_web.coad_drug_compounds (
  drug_slug,
  drug_name,
  compound_name,
  chembl_id,
  molregno,
  molecular_formula,
  canonical_smiles,
  standard_inchi_key,
  max_phase,
  molecule_type,
  structure_image_url_or_svg
)
SELECT
  d.drug_slug,
  d.drug_name,
  COALESCE(r.pref_name, d.drug_name),
  r.chembl_id,
  r.molregno,
  cp.full_molformula,
  cs.canonical_smiles,
  cs.standard_inchi_key,
  r.max_phase,
  r.molecule_type,
  CASE
    WHEN r.chembl_id IS NULL THEN NULL
    ELSE 'https://www.ebi.ac.uk/chembl/api/data/image/' || r.chembl_id || '.svg'
  END
FROM ranked_matches r
JOIN coad_web.coad_treatment_drugs d
  ON d.drug_slug = r.drug_slug
LEFT JOIN chembl.compound_properties cp
  ON cp.molregno = r.molregno
LEFT JOIN chembl.compound_structures cs
  ON cs.molregno = r.molregno;

INSERT INTO coad_web.coad_drug_indications (
  drug_slug,
  chembl_id,
  indication_text,
  mesh_heading,
  efo_term
)
SELECT
  c.drug_slug,
  c.chembl_id,
  COALESCE(di.mesh_heading, di.efo_term, 'Cancer treatment context from ChEMBL drug indication records'),
  di.mesh_heading,
  di.efo_term
FROM coad_web.coad_drug_compounds c
JOIN chembl.drug_indication di
  ON di.molregno = c.molregno;

CREATE INDEX IF NOT EXISTS mutation_gene_frequencies_display_idx
  ON coad_web.mutation_gene_frequencies(display_order);
CREATE INDEX IF NOT EXISTS mutation_hotspots_gene_idx
  ON coad_web.mutation_hotspots(gene_symbol, display_order);
CREATE INDEX IF NOT EXISTS coad_drug_compounds_chembl_idx
  ON coad_web.coad_drug_compounds(chembl_id);
CREATE INDEX IF NOT EXISTS coad_treatment_drugs_display_idx
  ON coad_web.coad_treatment_drugs(display_order);

ANALYZE coad_web.mutation_gene_frequencies;
ANALYZE coad_web.mutation_hotspots;
ANALYZE coad_web.protein_structure_targets;
ANALYZE coad_web.coad_treatment_drugs;
ANALYZE coad_web.coad_drug_compounds;
ANALYZE coad_web.coad_drug_indications;
